### ISSUE TITLE
Repeated evaluation of arguments And possible improvements

### ISSUE THREAD

**Issue by yjqww6** [jsmaniac/typed-map#1]
`> (map (begin (displayln 1) cons) '(1 2 3) '(4 5 6))
1
1
1
- : (Listof (Pairof Positive-Byte Positive-Byte))
'((1 . 4) (2 . 5) (3 . 6))
`

And, it seems like the 'generalize' function could be replaced by this one?
`(: gen (All (a) (case→
                 [Null → Null]
                 [(Listof a) → (Listof a)])))
(define (gen a) a)`

Moreover, is it better to restricted the use of 'set!' to only the end of iteration?

**Comment by SuzanneSoy** [comment]
Hi @yjqww6 !

Thanks for the report, I fixed the multiple evaluation problem.

I'm looking at the definition of `gen`. If I used this double-reverse trick, there probably was a good reason for that, so I'm trying to see if your suggestion brings in any unsuspected regressions.

I'm not sure what you mean by "better to restrict the use of `set!` to only the end of iteration'? Could you clarify? `set!` is already used right at the end of each iteration, just before calling the `loop` function again.

**Comment by yjqww6** [comment]
@jsmaniac Sorry my for poor explanation. I will paste a example tomorrow.

**Comment by yjqww6** [comment]
@jsmaniac Okay, I found what I say about 'set!' has a regression on the case of acc with a Rec type. Please forget it.
