### ISSUE TITLE
Imcompability on foldl.

### ISSUE THREAD

**Issue by yjqww6** [jsmaniac/typed-map#2]
with typed-map:
(foldl (λ (x [acc : (Rec R (U Null (Pairof R Positive-Index)))])
           (cons acc (add1 x)))
          '()
          '(1 2 3))
returns
'(((() . 4) . 3) . 2)

But in untyped racket
(foldl (λ (x acc)
           (cons acc (add1 x)))
                     '()
                     '(1 2 3))
returns 
'(((() . 2) . 3) . 4)

It seems there is a typo on the definition of foldl
    [(_ f init-acc lᵢ ...)
     (with-syntax ([(argᵢ ...) (generate-temporaries #'(lᵢ ...))])
#'(**foldr** (λ (argᵢ ... arg-acc) (f argᵢ ... arg-acc)) init-acc lᵢ ...))])

which should be
    [(_ f init-acc lᵢ ...)
     (with-syntax ([(argᵢ ...) (generate-temporaries #'(lᵢ ...))])
#'(**foldl** (λ (argᵢ ... arg-acc) (f argᵢ ... arg-acc)) init-acc lᵢ ...))]))

**Comment by SuzanneSoy** [comment]
@yjqww6 Thanks for the report! I had some tests for `foldl`, but unfortunately managed to skip this particular case :-( .

There's a fix coming in a couple of minutes. Sorry for the delay (we're not on the same timezone it seems!).
